name: L_BK_alternate
use_tb_logger: true
model:  L_BK_alternate

dataset:
  train:
    name: train
    dataroot: /home/zjc/dual_pixel/defocus-deblurring-dual-pixel-master/DPDNet/dd_dp_dataset_canon_patch
    filter:
    trainpairs: data/canon_coc_train_dataours.txt
    batch_size: 4
    image_size: 512
    max_iter: 40
    iter_size: 1
    workers: 4
    left_name: train_l/source
    right_name: train_r/source
    combine_name: train_c/target
    combine_source_name: train_c/source
    blur_name: /home/zjc/dual_pixel/defocus-deblurring-dual-pixel-master/DPDNet/dd_dp_dataset_canon_patch/train_b/source


  val:
    name: val
    dataroot: /home/zjc/dual_pixel/defocus-deblurring-dual-pixel-master/DPDNet/dd_dp_dataset_canon_patch
    batch_size: 1
    workers: 1
    left_name: val_l/source
    right_name: val_r/source
    combine_name: val_c/target
    combine_source_name: val_c/source
    blur_name: /home/zjc/dual_pixel/defocus-deblurring-dual-pixel-master/DPDNet/dd_dp_dataset_canon_patch/val_b/source

network_G:
  in_nc: 3
  block_num: 2
  init: xavier
  hidden_channels: 128
  K: 4

path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~ #/home/zjc/dual_pixel/BaMBNet-main/experiments/COCMAP_PARAM_TRAIN_GAN/models/25_models.pth
  
logger:
  print_freq: 10
  save_checkpoint_freq: 1 #!!float 5e3

train:
  lr: !!float 2e-5
  beta1: 0.9
  beta2: 0.999
  max_grad_norm: 20
  max_grad_clip: 20
  niter: 500000
  epoch: 30

  lr_steps: [30, 60, 120, 180]
  lr_gamma: 0.5

  val_freq: 1 #!!float 5e3
  manual_seed: 17
